# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Program-Project\DreamingLight-Launcher\UIs\HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(860, 500)
        Form.setMinimumSize(QtCore.QSize(860, 500))
        Form.setMaximumSize(QtCore.QSize(860, 500))
        self.LargeTitleLabel = LargeTitleLabel(Form)
        self.LargeTitleLabel.setGeometry(QtCore.QRect(45, 50, 796, 391))
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.LargeTitleLabel.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">你好~ヾ(≧▽≦*)o</span></p><p><span style=\" font-size:36pt;\">这里是</span><span style=\" font-size:36pt; font-weight:600;\">月梦初晓MC 启动器</span></p><p><span style=\" font-size:36pt; font-weight:600;\">这是主页balalala</span></p><p><span style=\" font-size:36pt; font-weight:600;\">（没想好放什么上去）</span></p></body></html>"))
from qfluentwidgets import LargeTitleLabel
