# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Document\Project\Dawnthia-Launcher\UIs\UIFILES\HomePage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(860, 500)
        HomePage.setMinimumSize(QtCore.QSize(860, 500))
        HomePage.setMaximumSize(QtCore.QSize(860, 500))
        self.TitleLabel = TitleLabel(HomePage)
        self.TitleLabel.setGeometry(QtCore.QRect(20, 20, 471, 31))
        self.TitleLabel.setObjectName("TitleLabel")
        self.VersionLabel = QtWidgets.QLabel(HomePage)
        self.VersionLabel.setGeometry(QtCore.QRect(750, 470, 72, 15))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.VersionLabel.setFont(font)
        self.VersionLabel.setObjectName("VersionLabel")

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "Form"))
        self.TitleLabel.setText(_translate("HomePage", "Welcome to 月梦初晓|Dawnthia !\n"
"\n"
""))
        self.VersionLabel.setText(_translate("HomePage", "Version"))
from qfluentwidgets import TitleLabel
