# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Document\Project\Dawnthia-Launcher\UIs\SettingsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsPage(object):
    def setupUi(self, SettingsPage):
        SettingsPage.setObjectName("SettingsPage")
        SettingsPage.resize(860, 500)
        self.SmoothScrollArea = SmoothScrollArea(SettingsPage)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(0, 0, 846, 491))
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 844, 489))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(SettingsPage)
        QtCore.QMetaObject.connectSlotsByName(SettingsPage)

    def retranslateUi(self, SettingsPage):
        _translate = QtCore.QCoreApplication.translate
        SettingsPage.setWindowTitle(_translate("SettingsPage", "Form"))
from qfluentwidgets import SmoothScrollArea
