# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Program-Project\DreamingLight-Launcher\UIs\Tools.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tools(object):
    def setupUi(self, Tools):
        Tools.setObjectName("Tools")
        Tools.resize(830, 830)
        Tools.setMinimumSize(QtCore.QSize(830, 830))
        Tools.setMaximumSize(QtCore.QSize(830, 830))
        self.gridLayoutWidget = QtWidgets.QWidget(Tools)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(5, 5, 816, 101))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleCard = HeaderCardWidget(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.TitleCard.setFont(font)
        self.TitleCard.setObjectName("TitleCard")
        self.WarningText = BodyLabel(self.TitleCard)
        self.WarningText.setGeometry(QtCore.QRect(15, 60, 776, 26))
        self.WarningText.setProperty("lightColor", QtGui.QColor(255, 0, 4))
        self.WarningText.setObjectName("WarningText")
        self.gridLayout.addWidget(self.TitleCard, 0, 0, 1, 1)

        self.retranslateUi(Tools)
        QtCore.QMetaObject.connectSlotsByName(Tools)

    def retranslateUi(self, Tools):
        _translate = QtCore.QCoreApplication.translate
        Tools.setWindowTitle(_translate("Tools", "Form"))
        self.TitleCard.setTitle(_translate("Tools", "这里是小工具合集...... 云云氢写的玩的(部分来自于互联网"))
        self.WarningText.setText(_translate("Tools", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">注意！</span><span style=\" font-size:12pt;\">使用工具前请先行查阅工作原理和其他资料 开发者不为此造成的后果任何责任！</span></p></body></html>"))
from qfluentwidgets import BodyLabel, HeaderCardWidget
