# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Program-Project\DreamingLight-Launcher\UIs\ToolsPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolsPage(object):
    def setupUi(self, ToolsPage):
        ToolsPage.setObjectName("ToolsPage")
        ToolsPage.resize(860, 500)
        self.SmoothScrollArea = SmoothScrollArea(ToolsPage)
        self.SmoothScrollArea.setGeometry(QtCore.QRect(10, 5, 836, 486))
        self.SmoothScrollArea.setWidgetResizable(True)
        self.SmoothScrollArea.setObjectName("SmoothScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 834, 484))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.SmoothScrollArea.setWidget(self.scrollAreaWidgetContents)

        self.retranslateUi(ToolsPage)
        QtCore.QMetaObject.connectSlotsByName(ToolsPage)

    def retranslateUi(self, ToolsPage):
        _translate = QtCore.QCoreApplication.translate
        ToolsPage.setWindowTitle(_translate("ToolsPage", "Form"))
from qfluentwidgets import SmoothScrollArea
